import {
  Country,
  DeliveryStatusEnum,
  ParcelTypeEnum,
  PaymentStatusEnum,
} from 'src/type';

export const JOURNEYS_MOCK = [
  {
    id: '55555',
    isCompleted: true,
    origin: Country.UNITED_KINGDOM,
    destination: Country.UKRAINE,
    departureDate: new Date().toJSON(),
    arrivalDate: null,
    journeyNumber: '111111',
    vehicle: {
      plateNumber: 'BO4050BO',
      model: 'Sprinter',
      brand: 'Mercedes',
      isActive: true,
      images: null,
      manufactureYear: '2015',
    },
    parcels: [
      {
        id: '21',
        sender: {
          id: '1231',
          firstName: 'Андрій',
          lastName: 'Пилипець',
          phone: '7950955123',
          isBlocked: false,
          comment: null,
          address: {
            city: 'Лондон',
            street: 'Brompton Road',
            country: 'Великобританія',
            postCode: 'SW3 1ER',
            building: null,
            apartment: null,
          },
        },
        recipient: {
          id: '32123',
          firstName: 'Роман',
          lastName: 'Цурай',
          phone: '380973341234',
          isBlocked: false,
          comment: null,
          address: {
            city: 'Львів',
            street: 'Заводська',
            country: 'Україна',
            postCode: '79001',
            building: '10',
            apartment: '1',
          },
        },
        weight: 150,
        type: ParcelTypeEnum.Regular,
        notes: null,
        isLost: false,
        moneyAmount: null,
        pickupDate: new Date().toJSON(),
        deliveryDate: null,
        journeyId: '55555',
        isArchived: false,
        price: 72,
        discount: null,
        discountType: null,
        images: [],
        hasBorderCheck: false,
        isDamaged: false,
        deliveryStatus: DeliveryStatusEnum.InProgress,
        paymentStatus: PaymentStatusEnum.Paid,
      },
      {
        id: '22',
        sender: {
          id: '1232',
          firstName: 'Ігор',
          lastName: 'Заремба',
          phone: '7950955124',
          isBlocked: false,
          comment: null,
          address: {
            city: 'Лондон',
            street: 'Cromwell Road',
            country: 'Великобританія',
            postCode: 'SW3 2EB',
            building: null,
            apartment: null,
          },
        },
        recipient: {
          id: '32123',
          firstName: 'Іван',
          lastName: 'Гуда',
          phone: '380973343214',
          isBlocked: false,
          comment: null,
          address: {
            city: 'Тернопіль',
            street: 'Текстильника',
            country: 'Україна',
            postCode: '46001',
            building: '21',
            apartment: '15',
          },
        },
        weight: 150,
        type: ParcelTypeEnum.Regular,
        notes: null,
        isLost: false,
        moneyAmount: null,
        pickupDate: new Date().toJSON(),
        deliveryDate: null,
        journeyId: '55555',
        isArchived: false,
        price: 72,
        discount: null,
        discountType: null,
        images: [],
        hasBorderCheck: false,
        isDamaged: false,
        deliveryStatus: DeliveryStatusEnum.InProgress,
        paymentStatus: PaymentStatusEnum.Paid,
      },
    ],
  },
  {
    id: '55556',
    isCompleted: true,
    origin: Country.UNITED_KINGDOM,
    destination: Country.UKRAINE,
    departureDate: new Date().toJSON(),
    arrivalDate: null,
    journeyNumber: '222222',
    vehicle: {
      plateNumber: 'BO1878ЕВ',
      model: 'Sprinter',
      brand: 'Mercedes',
      isActive: true,
      images: null,
      manufactureYear: '2015',
    },
    parcels: [
      {
        id: '21',
        sender: {
          id: '1231',
          firstName: 'Андрій',
          lastName: 'Пилипець',
          phone: '7950955123',
          isBlocked: false,
          comment: null,
          address: {
            city: 'Лондон',
            street: 'Brompton Road',
            country: 'Великобританія',
            postCode: 'SW3 1ER',
            building: null,
            apartment: null,
          },
        },
        recipient: {
          id: '32123',
          firstName: 'Роман',
          lastName: 'Цурай',
          phone: '380973341234',
          isBlocked: false,
          comment: null,
          address: {
            city: 'Львів',
            street: 'Заводська',
            country: 'Україна',
            postCode: '79001',
            building: '10',
            apartment: '1',
          },
        },
        weight: 150,
        type: ParcelTypeEnum.Regular,
        notes: null,
        isLost: false,
        moneyAmount: null,
        pickupDate: new Date().toJSON(),
        deliveryDate: null,
        journeyId: '55555',
        isArchived: false,
        price: 72,
        discount: null,
        discountType: null,
        images: [],
        hasBorderCheck: false,
        isDamaged: false,
        deliveryStatus: DeliveryStatusEnum.InProgress,
        paymentStatus: PaymentStatusEnum.Paid,
      },
      {
        id: '22',
        sender: {
          id: '1232',
          firstName: 'Ігор',
          lastName: 'Заремба',
          phone: '7950955124',
          isBlocked: false,
          comment: null,
          address: {
            city: 'Лондон',
            street: 'Cromwell Road',
            country: 'Великобританія',
            postCode: 'SW3 2EB',
            building: null,
            apartment: null,
          },
        },
        recipient: {
          id: '32123',
          firstName: 'Іван',
          lastName: 'Гуда',
          phone: '380973343214',
          isBlocked: false,
          comment: null,
          address: {
            city: 'Тернопіль',
            street: 'Текстильника',
            country: 'Україна',
            postCode: '46001',
            building: '21',
            apartment: '15',
          },
        },
        weight: 150,
        type: ParcelTypeEnum.Regular,
        notes: null,
        isLost: false,
        moneyAmount: null,
        pickupDate: new Date().toJSON(),
        deliveryDate: null,
        journeyId: '55555',
        isArchived: false,
        price: 72,
        discount: null,
        discountType: null,
        images: [],
        hasBorderCheck: false,
        isDamaged: false,
        deliveryStatus: DeliveryStatusEnum.InProgress,
        paymentStatus: PaymentStatusEnum.Paid,
      },
    ],
  },
  {
    id: '55557',
    isCompleted: true,
    origin: Country.UNITED_KINGDOM,
    destination: Country.UKRAINE,
    departureDate: new Date().toJSON(),
    arrivalDate: null,
    journeyNumber: '333333',
    vehicle: {
      plateNumber: 'BO2412BO',
      model: 'Sprinter',
      brand: 'Mercedes',
      isActive: true,
      images: null,
      manufactureYear: '2015',
    },
    parcels: [
      {
        id: '21',
        sender: {
          id: '1231',
          firstName: 'Андрій',
          lastName: 'Пилипець',
          phone: '7950955123',
          isBlocked: false,
          comment: null,
          address: {
            city: 'Лондон',
            street: 'Brompton Road',
            country: 'Великобританія',
            postCode: 'SW3 1ER',
            building: null,
            apartment: null,
          },
        },
        recipient: {
          id: '32123',
          firstName: 'Роман',
          lastName: 'Цурай',
          phone: '380973341234',
          isBlocked: false,
          comment: null,
          address: {
            city: 'Львів',
            street: 'Заводська',
            country: 'Україна',
            postCode: '79001',
            building: '10',
            apartment: '1',
          },
        },
        weight: 150,
        type: ParcelTypeEnum.Regular,
        notes: null,
        isLost: false,
        moneyAmount: null,
        pickupDate: new Date().toJSON(),
        deliveryDate: null,
        journeyId: '55555',
        isArchived: false,
        price: 72,
        discount: null,
        discountType: null,
        images: [],
        hasBorderCheck: false,
        isDamaged: false,
        deliveryStatus: DeliveryStatusEnum.InProgress,
        paymentStatus: PaymentStatusEnum.Paid,
      },
      {
        id: '22',
        sender: {
          id: '1232',
          firstName: 'Ігор',
          lastName: 'Заремба',
          phone: '7950955124',
          isBlocked: false,
          comment: null,
          address: {
            city: 'Лондон',
            street: 'Cromwell Road',
            country: 'Великобританія',
            postCode: 'SW3 2EB',
            building: null,
            apartment: null,
          },
        },
        recipient: {
          id: '32123',
          firstName: 'Іван',
          lastName: 'Гуда',
          phone: '380973343214',
          isBlocked: false,
          comment: null,
          address: {
            city: 'Тернопіль',
            street: 'Текстильника',
            country: 'Україна',
            postCode: '46001',
            building: '21',
            apartment: '15',
          },
        },
        weight: 150,
        type: ParcelTypeEnum.Regular,
        notes: null,
        isLost: false,
        moneyAmount: null,
        pickupDate: new Date().toJSON(),
        deliveryDate: null,
        journeyId: '55555',
        isArchived: false,
        price: 72,
        discount: null,
        discountType: null,
        images: [],
        hasBorderCheck: false,
        isDamaged: false,
        deliveryStatus: DeliveryStatusEnum.InProgress,
        paymentStatus: PaymentStatusEnum.Paid,
      },
    ],
  },
  {
    id: '55558',
    isCompleted: true,
    origin: Country.UNITED_KINGDOM,
    destination: Country.UKRAINE,
    departureDate: new Date().toJSON(),
    arrivalDate: null,
    journeyNumber: '444444',
    vehicle: {
      plateNumber: 'BO2012BO',
      model: 'Sprinter',
      brand: 'Mercedes',
      isActive: true,
      images: null,
      manufactureYear: '2015',
    },
    parcels: [
      {
        id: '21',
        sender: {
          id: '1231',
          firstName: 'Андрій',
          lastName: 'Пилипець',
          phone: '7950955123',
          isBlocked: false,
          comment: null,
          address: {
            city: 'Лондон',
            street: 'Brompton Road',
            country: 'Великобританія',
            postCode: 'SW3 1ER',
            building: null,
            apartment: null,
          },
        },
        recipient: {
          id: '32123',
          firstName: 'Роман',
          lastName: 'Цурай',
          phone: '380973341234',
          isBlocked: false,
          comment: null,
          address: {
            city: 'Львів',
            street: 'Заводська',
            country: 'Україна',
            postCode: '79001',
            building: '10',
            apartment: '1',
          },
        },
        weight: 150,
        type: ParcelTypeEnum.Regular,
        notes: null,
        isLost: false,
        moneyAmount: null,
        pickupDate: new Date().toJSON(),
        deliveryDate: null,
        journeyId: '55555',
        isArchived: false,
        price: 72,
        discount: null,
        discountType: null,
        images: [],
        hasBorderCheck: false,
        isDamaged: false,
        deliveryStatus: DeliveryStatusEnum.InProgress,
        paymentStatus: PaymentStatusEnum.Paid,
      },
      {
        id: '22',
        sender: {
          id: '1232',
          firstName: 'Ігор',
          lastName: 'Заремба',
          phone: '7950955124',
          isBlocked: false,
          comment: null,
          address: {
            city: 'Лондон',
            street: 'Cromwell Road',
            country: 'Великобританія',
            postCode: 'SW3 2EB',
            building: null,
            apartment: null,
          },
        },
        recipient: {
          id: '32123',
          firstName: 'Іван',
          lastName: 'Гуда',
          phone: '380973343214',
          isBlocked: false,
          comment: null,
          address: {
            city: 'Тернопіль',
            street: 'Текстильника',
            country: 'Україна',
            postCode: '46001',
            building: '21',
            apartment: '15',
          },
        },
        weight: 150,
        type: ParcelTypeEnum.Regular,
        notes: null,
        isLost: false,
        moneyAmount: null,
        pickupDate: new Date().toJSON(),
        deliveryDate: null,
        journeyId: '55555',
        isArchived: false,
        price: 72,
        discount: null,
        discountType: null,
        images: [],
        hasBorderCheck: false,
        isDamaged: false,
        deliveryStatus: DeliveryStatusEnum.InProgress,
        paymentStatus: PaymentStatusEnum.Paid,
      },
    ],
  },
  {
    id: '55559',
    isCompleted: true,
    origin: Country.UNITED_KINGDOM,
    destination: Country.UKRAINE,
    departureDate: new Date().toJSON(),
    arrivalDate: null,
    journeyNumber: '555555',
    vehicle: {
      plateNumber: 'BO2322BO',
      model: 'Sprinter',
      brand: 'Mercedes',
      isActive: true,
      images: null,
      manufactureYear: '2015',
    },
    parcels: [
      {
        id: '21',
        sender: {
          id: '1231',
          firstName: 'Андрій',
          lastName: 'Пилипець',
          phone: '7950955123',
          isBlocked: false,
          comment: null,
          address: {
            city: 'Лондон',
            street: 'Brompton Road',
            country: 'Великобританія',
            postCode: 'SW3 1ER',
            building: null,
            apartment: null,
          },
        },
        recipient: {
          id: '32123',
          firstName: 'Роман',
          lastName: 'Цурай',
          phone: '380973341234',
          isBlocked: false,
          comment: null,
          address: {
            city: 'Львів',
            street: 'Заводська',
            country: 'Україна',
            postCode: '79001',
            building: '10',
            apartment: '1',
          },
        },
        weight: 150,
        type: ParcelTypeEnum.Regular,
        notes: null,
        isLost: false,
        moneyAmount: null,
        pickupDate: new Date().toJSON(),
        deliveryDate: null,
        journeyId: '55555',
        isArchived: false,
        price: 72,
        discount: null,
        discountType: null,
        images: [],
        hasBorderCheck: false,
        isDamaged: false,
        deliveryStatus: DeliveryStatusEnum.InProgress,
        paymentStatus: PaymentStatusEnum.Paid,
      },
      {
        id: '22',
        sender: {
          id: '1232',
          firstName: 'Ігор',
          lastName: 'Заремба',
          phone: '7950955124',
          isBlocked: false,
          comment: null,
          address: {
            city: 'Лондон',
            street: 'Cromwell Road',
            country: 'Великобританія',
            postCode: 'SW3 2EB',
            building: null,
            apartment: null,
          },
        },
        recipient: {
          id: '32123',
          firstName: 'Іван',
          lastName: 'Гуда',
          phone: '380973343214',
          isBlocked: false,
          comment: null,
          address: {
            city: 'Тернопіль',
            street: 'Текстильника',
            country: 'Україна',
            postCode: '46001',
            building: '21',
            apartment: '15',
          },
        },
        weight: 150,
        type: ParcelTypeEnum.Regular,
        notes: null,
        isLost: false,
        moneyAmount: null,
        pickupDate: new Date().toJSON(),
        deliveryDate: null,
        journeyId: '55555',
        isArchived: false,
        price: 72,
        discount: null,
        discountType: null,
        images: [],
        hasBorderCheck: false,
        isDamaged: false,
        deliveryStatus: DeliveryStatusEnum.InProgress,
        paymentStatus: PaymentStatusEnum.Paid,
      },
    ],
  },
  {
    id: '60000',
    isCompleted: true,
    origin: Country.UNITED_KINGDOM,
    destination: Country.UKRAINE,
    departureDate: new Date().toJSON(),
    arrivalDate: null,
    journeyNumber: '666666',
    vehicle: {
      plateNumber: 'BO9844BO',
      model: 'Sprinter',
      brand: 'Mercedes',
      isActive: true,
      images: null,
      manufactureYear: '2015',
    },
    parcels: [
      {
        id: '21',
        sender: {
          id: '1231',
          firstName: 'Андрій',
          lastName: 'Пилипець',
          phone: '7950955123',
          isBlocked: false,
          comment: null,
          address: {
            city: 'Лондон',
            street: 'Brompton Road',
            country: 'Великобританія',
            postCode: 'SW3 1ER',
            building: null,
            apartment: null,
          },
        },
        recipient: {
          id: '32123',
          firstName: 'Роман',
          lastName: 'Цурай',
          phone: '380973341234',
          isBlocked: false,
          comment: null,
          address: {
            city: 'Львів',
            street: 'Заводська',
            country: 'Україна',
            postCode: '79001',
            building: '10',
            apartment: '1',
          },
        },
        weight: 150,
        type: ParcelTypeEnum.Regular,
        notes: null,
        isLost: false,
        moneyAmount: null,
        pickupDate: new Date().toJSON(),
        deliveryDate: null,
        journeyId: '55555',
        isArchived: false,
        price: 72,
        discount: null,
        discountType: null,
        images: [],
        hasBorderCheck: false,
        isDamaged: false,
        deliveryStatus: DeliveryStatusEnum.InProgress,
        paymentStatus: PaymentStatusEnum.Paid,
      },
      {
        id: '22',
        sender: {
          id: '1232',
          firstName: 'Ігор',
          lastName: 'Заремба',
          phone: '7950955124',
          isBlocked: false,
          comment: null,
          address: {
            city: 'Лондон',
            street: 'Cromwell Road',
            country: 'Великобританія',
            postCode: 'SW3 2EB',
            building: null,
            apartment: null,
          },
        },
        recipient: {
          id: '32123',
          firstName: 'Іван',
          lastName: 'Гуда',
          phone: '380973343214',
          isBlocked: false,
          comment: null,
          address: {
            city: 'Тернопіль',
            street: 'Текстильника',
            country: 'Україна',
            postCode: '46001',
            building: '21',
            apartment: '15',
          },
        },
        weight: 150,
        type: ParcelTypeEnum.Regular,
        notes: null,
        isLost: false,
        moneyAmount: null,
        pickupDate: new Date().toJSON(),
        deliveryDate: null,
        journeyId: '55555',
        isArchived: false,
        price: 72,
        discount: null,
        discountType: null,
        images: [],
        hasBorderCheck: false,
        isDamaged: false,
        deliveryStatus: DeliveryStatusEnum.InProgress,
        paymentStatus: PaymentStatusEnum.Paid,
      },
    ],
  },
  {
    id: '60001',
    isCompleted: true,
    origin: Country.UNITED_KINGDOM,
    destination: Country.UKRAINE,
    departureDate: new Date().toJSON(),
    arrivalDate: null,
    journeyNumber: '777777',
    vehicle: {
      plateNumber: 'BO1166BO',
      model: 'Sprinter',
      brand: 'Mercedes',
      isActive: true,
      images: null,
      manufactureYear: '2015',
    },
    parcels: [
      {
        id: '21',
        sender: {
          id: '1231',
          firstName: 'Андрій',
          lastName: 'Пилипець',
          phone: '7950955123',
          isBlocked: false,
          comment: null,
          address: {
            city: 'Лондон',
            street: 'Brompton Road',
            country: 'Великобританія',
            postCode: 'SW3 1ER',
            building: null,
            apartment: null,
          },
        },
        recipient: {
          id: '32123',
          firstName: 'Роман',
          lastName: 'Цурай',
          phone: '380973341234',
          isBlocked: false,
          comment: null,
          address: {
            city: 'Львів',
            street: 'Заводська',
            country: 'Україна',
            postCode: '79001',
            building: '10',
            apartment: '1',
          },
        },
        weight: 150,
        type: ParcelTypeEnum.Regular,
        notes: null,
        isLost: false,
        moneyAmount: null,
        pickupDate: new Date().toJSON(),
        deliveryDate: null,
        journeyId: '55555',
        isArchived: false,
        price: 72,
        discount: null,
        discountType: null,
        images: [],
        hasBorderCheck: false,
        isDamaged: false,
        deliveryStatus: DeliveryStatusEnum.InProgress,
        paymentStatus: PaymentStatusEnum.Paid,
      },
      {
        id: '22',
        sender: {
          id: '1232',
          firstName: 'Ігор',
          lastName: 'Заремба',
          phone: '7950955124',
          isBlocked: false,
          comment: null,
          address: {
            city: 'Лондон',
            street: 'Cromwell Road',
            country: 'Великобританія',
            postCode: 'SW3 2EB',
            building: null,
            apartment: null,
          },
        },
        recipient: {
          id: '32123',
          firstName: 'Іван',
          lastName: 'Гуда',
          phone: '380973343214',
          isBlocked: false,
          comment: null,
          address: {
            city: 'Тернопіль',
            street: 'Текстильника',
            country: 'Україна',
            postCode: '46001',
            building: '21',
            apartment: '15',
          },
        },
        weight: 150,
        type: ParcelTypeEnum.Regular,
        notes: null,
        isLost: false,
        moneyAmount: null,
        pickupDate: new Date().toJSON(),
        deliveryDate: null,
        journeyId: '55555',
        isArchived: false,
        price: 72,
        discount: null,
        discountType: null,
        images: [],
        hasBorderCheck: false,
        isDamaged: false,
        deliveryStatus: DeliveryStatusEnum.InProgress,
        paymentStatus: PaymentStatusEnum.Paid,
      },
    ],
  },
];
