export const CLIENTS_MOCK = [
  {
    id: '1',
    phone: '+38 093 444 44 44',
    lastName: 'Корчук',
    firstName: 'Аня',
    isBlocked: false,
    comment: null,
    address: {
      city: 'Київ',
      street: 'Шевченка 15',
      country: 'Україна',
      postCode: '41000',
      building: null,
      apartment: null,
    },
  },
  {
    id: '2',
    phone: '+38 063 567 23 48',
    lastName: 'Семенюк',
    firstName: 'Андрій',
    isBlocked: false,
    comment: null,
    address: {
      city: 'Львів',
      street: 'Оболоння 8',
      country: 'Україна',
      postCode: '42000',
      building: null,
      apartment: null,
    },
  },
  {
    id: '3',
    phone: '+38 093 129 64 14',
    lastName: 'Мілтон',
    firstName: 'Кейт',
    isBlocked: false,
    comment: null,
    address: {
      city: 'Лондон',
      street: 'Harley Street',
      country: 'Велика Британія',
      postCode: '21000',
      building: null,
      apartment: null,
    },
  },
];
