import {
  Country,
  DeliveryStatusEnum,
  ParcelTypeEnum,
  PaymentStatusEnum,
  UserTypesEnum,
} from 'src/type';

export const DRIVER_MOCK = {
  id: '1332',
  firstName: 'Дмитро',
  lastName: 'Гнатюк',
  email: 'dmytro@gmail.com',
  uaPhone: '380971233211',
  ukPhone: null,
  isAdmin: false,
  isSuperAdmin: false,
  type: UserTypesEnum.Driver,
  isBlocked: false,
  imageUrl: null,
};

export const JOURNEY_MOCK = {
  id: '55555',
  isCompleted: false,
  origin: Country.UKRAINE,
  destination: Country.UNITED_KINGDOM,
  departureDate: new Date().toJSON(),
  arrivalDate: null,
  journeyNumber: '331231',
  vehicle: {
    plateNumber: 'BO3211BO',
    model: 'Sprinter',
    brand: 'Mercedes',
    isActive: true,
    images: null,
    manufactureYear: '2015',
  },
  drivers: [
    {
      id: '111',
      firstName: 'Дмитро',
      lastName: 'Гнатюк',
      email: 'dmytro@gmail.com',
      uaPhone: '380971233211',
      ukPhone: null,
      isAdmin: false,
      isSuperAdmin: false,
      type: UserTypesEnum.Driver,
      isBlocked: false,
      imageUrl: null,
    },
    {
      id: '222',
      firstName: 'Карпо',
      lastName: 'Чумак',
      email: 'karpo@gmail.com',
      uaPhone: '380978872341',
      ukPhone: null,
      isAdmin: false,
      isSuperAdmin: false,
      type: UserTypesEnum.Driver,
      isBlocked: false,
      imageUrl: null,
    },
  ],
  parcels: [
    {
      id: '21',
      sender: {
        id: '1231',
        firstName: 'Андрій',
        lastName: 'Пилипець',
        phone: '7950955123',
        isBlocked: false,
        comment: null,
        address: {
          city: 'Лондон',
          street: 'Brompton Road',
          country: 'Великобританія',
          postCode: 'SW3 1ER',
          building: null,
          apartment: null,
        },
      },
      recipient: {
        id: '32123',
        firstName: 'Роман',
        lastName: 'Цурай',
        phone: '380973341234',
        isBlocked: false,
        comment: null,
        address: {
          city: 'Львів',
          street: 'Заводська',
          country: 'Україна',
          postCode: '79001',
          building: '10',
          apartment: '1',
        },
      },
      weight: 150,
      type: ParcelTypeEnum.Regular,
      notes: null,
      isLost: false,
      moneyAmount: null,
      pickupDate: new Date().toJSON(),
      deliveryDate: null,
      journeyId: '55555',
      isArchived: false,
      price: 72,
      discount: null,
      discountType: null,
      images: [],
      hasBorderCheck: false,
      isDamaged: false,
      deliveryStatus: DeliveryStatusEnum.InProgress,
      paymentStatus: PaymentStatusEnum.Paid,
    },
    {
      id: '22',
      sender: {
        id: '1232',
        firstName: 'Ігор',
        lastName: 'Заремба',
        phone: '7950955124',
        isBlocked: false,
        comment: null,
        address: {
          city: 'Лондон',
          street: 'Cromwell Road',
          country: 'Великобританія',
          postCode: 'SW3 2EB',
          building: null,
          apartment: null,
        },
      },
      recipient: {
        id: '32123',
        firstName: 'Іван',
        lastName: 'Гуда',
        phone: '380973343214',
        isBlocked: false,
        comment: null,
        address: {
          city: 'Тернопіль',
          street: 'Текстильника',
          country: 'Україна',
          postCode: '46001',
          building: '21',
          apartment: '15',
        },
      },
      weight: 150,
      type: ParcelTypeEnum.Regular,
      notes: null,
      isLost: false,
      moneyAmount: null,
      pickupDate: new Date().toJSON(),
      deliveryDate: null,
      journeyId: '55555',
      isArchived: false,
      price: 72,
      discount: null,
      discountType: null,
      images: [],
      hasBorderCheck: false,
      isDamaged: false,
      deliveryStatus: DeliveryStatusEnum.InProgress,
      paymentStatus: PaymentStatusEnum.Paid,
    },
  ],
};
